name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and publis it to Azure container registry
      run: |
          docker build . --file dockerfile --tag dkidemo.azurecr.io/demo-angular-app:latest;
          docker login dkidemo.azurecr.io -p ${{ secrets.AZURE_CONTAINER_REGISTRY_PW }} -u dkidemo;
          docker push dkidemo.azurecr.io/demo-angular-app:latest
